#!/usr/bin/env python3
"""Static QR codes for the slides: they never change, because the laptop's own hotspot always
gives it the same address (192.168.137.1) and the pairing token is fixed in backend/.env.
Change the code and restart as often as you like - the printed codes keep working.

  python scripts/static_qr.py --ssid "<hotspot name>" --password "<hotspot password>"
      [--ip 192.168.137.1] [--port 8443] [--out ../qr]

Writes (the folder is gitignored - the codes carry the pairing token and the Wi-Fi password):
  1-wifi.png         join the laptop's hotspot (standard Wi-Fi QR: phone cameras connect directly)
  2-certificate.png  first time per phone: install the local certificate (no warnings after)
  3-app.png          open the app, already paired
  slide.png          all three side by side with captions, ready for a slide
  README.txt         what each code holds
start.ps1 regenerates them on every start with the hotspot on; the content only changes if the
token, the hotspot name/password or the port change.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

HOTSPOT_IP = "192.168.137.1"  # Windows Mobile Hotspot's own address, the same on every PC


def wifi_payload(ssid: str, password: str) -> str:
    """The de-facto standard Wi-Fi QR ("WIFI:T:WPA;S:...;P:...;;") that phone cameras understand."""
    def esc(value: str) -> str:
        return "".join("\\" + c if c in '\\;,:"' else c for c in value)
    return f"WIFI:T:WPA;S:{esc(ssid)};P:{esc(password)};;"


def urls(ip: str, port: int, token: str) -> dict:
    base = f"https://{ip}:{port}"
    return {"certificate": f"{base}/ca.crt", "app": f"{base}/?token={token}&detect=1"}


def qr_image(data: str):
    import qrcode
    from qrcode.constants import ERROR_CORRECT_Q

    qr = qrcode.QRCode(error_correction=ERROR_CORRECT_Q, box_size=16, border=4)  # 4 = the standard quiet zone
    qr.add_data(data)
    qr.make(fit=True)
    return qr.make_image(fill_color="black", back_color="white").convert("RGB")


def _font(size: int):
    from PIL import ImageFont

    for name in ("arialbd.ttf", "arial.ttf", "DejaVuSans-Bold.ttf", "DejaVuSans.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return None  # no font with Greek letters: captions in English only


def slide(images: list, captions: list[tuple[str, str]]):
    from PIL import Image, ImageDraw

    side = 640
    pad = 48
    title_font, text_font = _font(44), _font(32)
    header = 200 if title_font else 80
    card = Image.new("RGB", (len(images) * (side + pad) + pad, header + side + pad), "white")
    draw = ImageDraw.Draw(card)
    for i, (img, (el, en)) in enumerate(zip(images, captions)):
        x = pad + i * (side + pad)
        if title_font:
            draw.text((x, 40), el, fill="black", font=title_font)
            draw.text((x, 110), en, fill=(90, 90, 90), font=text_font)
        else:
            draw.text((x, 30), en, fill="black")
        card.paste(img.resize((side, side)), (x, header))
    return card


def write(out: Path, ip: str, port: int, token: str, ssid: str, password: str) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    links = urls(ip, port, token)
    codes = [
        ("1-wifi.png", wifi_payload(ssid, password), ("1. Σύνδεση στο Wi-Fi", f"Join the Wi-Fi: {ssid}")),
        ("2-certificate.png", links["certificate"], ("2. Πιστοποιητικό (μία φορά)", "Certificate - first time only")),
        ("3-app.png", links["app"], ("3. Άνοιξε την εφαρμογή", "Open the Cooking Assistant")),
    ]
    images = []
    for name, data, _ in codes:
        img = qr_image(data)
        img.save(out / name)
        images.append(img)
    slide(images, [c[2] for c in codes]).save(out / "slide.png")
    (out / "README.txt").write_text(
        "Static QR codes for the slides (regenerated by start.ps1; same content every time).\n\n"
        f"1-wifi.png         Wi-Fi '{ssid}' - the laptop's hotspot (turned on by start.ps1)\n"
        f"2-certificate.png  {links['certificate']}  - first time per phone: install it\n"
        f"3-app.png          {links['app']}\n"
        "slide.png          all three with captions\n\n"
        "They carry the pairing token and the Wi-Fi password: keep them out of git (this folder is ignored).\n",
        encoding="utf-8",
    )
    return {"out": str(out), **links}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ssid", required=True)
    ap.add_argument("--password", required=True)
    ap.add_argument("--ip", default=HOTSPOT_IP)
    ap.add_argument("--port", type=int, default=8443)
    ap.add_argument("--out", type=Path, default=BACKEND_DIR.parent / "qr")
    args = ap.parse_args(argv)
    try:
        import qrcode  # noqa: F401
    except ImportError:
        print("  (static QR codes skipped - qrcode not installed; re-run setup)")
        return 0
    import lan

    token, _ = lan.ensure_token()
    info = write(args.out, args.ip, args.port, token, args.ssid, args.password)
    print(f"  Slide QR codes (never change): {Path(info['out']) / 'slide.png'}  (1-wifi, 2-certificate, 3-app)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
